/**
 * generated by Xtext 2.12.0
 */
package fr.imta.clementdamien.dsl.selenium.mySelenium;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assert Equals</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imta.clementdamien.dsl.selenium.mySelenium.AssertEquals#getAssertableElement <em>Assertable Element</em>}</li>
 * </ul>
 *
 * @see fr.imta.clementdamien.dsl.selenium.mySelenium.MySeleniumPackage#getAssertEquals()
 * @model
 * @generated
 */
public interface AssertEquals extends Statement
{
  /**
   * Returns the value of the '<em><b>Assertable Element</b></em>' containment reference list.
   * The list contents are of type {@link fr.imta.clementdamien.dsl.selenium.mySelenium.AssertableElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Assertable Element</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assertable Element</em>' containment reference list.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.MySeleniumPackage#getAssertEquals_AssertableElement()
   * @model containment="true"
   * @generated
   */
  EList<AssertableElement> getAssertableElement();

} // AssertEquals
