/**
 * generated by Xtext 2.12.0
 */
package fr.imta.clementdamien.dsl.selenium.mySelenium;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.imta.clementdamien.dsl.selenium.mySelenium.MySeleniumFactory
 * @model kind="package"
 * @generated
 */
public interface MySeleniumPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mySelenium";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.imta.fr/clementdamien/dsl/selenium/MySelenium";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mySelenium";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MySeleniumPackage eINSTANCE = fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.ProgramImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Functions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__FUNCTIONS = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__STATEMENTS = 1;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionsImpl <em>Functions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionsImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getFunctions()
   * @generated
   */
  int FUNCTIONS = 1;

  /**
   * The feature id for the '<em><b>Functions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTIONS__FUNCTIONS = 0;

  /**
   * The number of structural features of the '<em>Functions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTIONS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.StatementsImpl <em>Statements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.StatementsImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getStatements()
   * @generated
   */
  int STATEMENTS = 2;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENTS__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Statements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__PARAMS = 1;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__STATEMENTS = 2;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionNameImpl <em>Function Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionNameImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getFunctionName()
   * @generated
   */
  int FUNCTION_NAME = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_NAME__NAME = 0;

  /**
   * The number of structural features of the '<em>Function Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.StatementImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 7;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionCallImpl <em>Function Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionCallImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getFunctionCall()
   * @generated
   */
  int FUNCTION_CALL = 5;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL__REF = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL__PARAMS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Function Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AssertableElementImpl <em>Assertable Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AssertableElementImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getAssertableElement()
   * @generated
   */
  int ASSERTABLE_ELEMENT = 10;

  /**
   * The number of structural features of the '<em>Assertable Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERTABLE_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.ProjectionImpl <em>Projection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.ProjectionImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getProjection()
   * @generated
   */
  int PROJECTION = 6;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTION__SELECTOR = ASSERTABLE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Projection Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTION__PROJECTION_ACTION = ASSERTABLE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Projection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTION_FEATURE_COUNT = ASSERTABLE_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AssertEqualsImpl <em>Assert Equals</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AssertEqualsImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getAssertEquals()
   * @generated
   */
  int ASSERT_EQUALS = 8;

  /**
   * The feature id for the '<em><b>Assertable Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERT_EQUALS__ASSERTABLE_ELEMENT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Assert Equals</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERT_EQUALS_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AssertContainsImpl <em>Assert Contains</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AssertContainsImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getAssertContains()
   * @generated
   */
  int ASSERT_CONTAINS = 9;

  /**
   * The feature id for the '<em><b>Container</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERT_CONTAINS__CONTAINER = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERT_CONTAINS__ELEMENT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Assert Contains</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERT_CONTAINS_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.NavigationActionImpl <em>Navigation Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.NavigationActionImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getNavigationAction()
   * @generated
   */
  int NAVIGATION_ACTION = 11;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAVIGATION_ACTION__ACTION = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAVIGATION_ACTION__PARAM = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Navigation Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAVIGATION_ACTION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.OneParameterActionImpl <em>One Parameter Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.OneParameterActionImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getOneParameterAction()
   * @generated
   */
  int ONE_PARAMETER_ACTION = 12;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONE_PARAMETER_ACTION__ACTION = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONE_PARAMETER_ACTION__SELECTOR = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Selector Parameter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONE_PARAMETER_ACTION__SELECTOR_PARAMETER = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>String Parameter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONE_PARAMETER_ACTION__STRING_PARAMETER = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>One Parameter Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONE_PARAMETER_ACTION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.TwoParametersActionImpl <em>Two Parameters Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.TwoParametersActionImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getTwoParametersAction()
   * @generated
   */
  int TWO_PARAMETERS_ACTION = 13;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TWO_PARAMETERS_ACTION__ACTION = 0;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TWO_PARAMETERS_ACTION__SELECTOR = 1;

  /**
   * The feature id for the '<em><b>Parameter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TWO_PARAMETERS_ACTION__PARAMETER = 2;

  /**
   * The number of structural features of the '<em>Two Parameters Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TWO_PARAMETERS_ACTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.SelectorImpl <em>Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.SelectorImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getSelector()
   * @generated
   */
  int SELECTOR = 14;

  /**
   * The feature id for the '<em><b>Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__ELEMENT = 0;

  /**
   * The feature id for the '<em><b>Attrs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__ATTRS = 1;

  /**
   * The feature id for the '<em><b>All</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__ALL = 2;

  /**
   * The number of structural features of the '<em>Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AttributesImpl <em>Attributes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AttributesImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getAttributes()
   * @generated
   */
  int ATTRIBUTES = 15;

  /**
   * The feature id for the '<em><b>Attrs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTES__ATTRS = 0;

  /**
   * The number of structural features of the '<em>Attributes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AttributeImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__VALUE = 1;

  /**
   * The feature id for the '<em><b>Val</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__VAL = 2;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionParametersImpl <em>Function Parameters</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionParametersImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getFunctionParameters()
   * @generated
   */
  int FUNCTION_PARAMETERS = 17;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_PARAMETERS__VARIABLES = 0;

  /**
   * The number of structural features of the '<em>Function Parameters</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_PARAMETERS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionCallParametersImpl <em>Function Call Parameters</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionCallParametersImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getFunctionCallParameters()
   * @generated
   */
  int FUNCTION_CALL_PARAMETERS = 18;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_PARAMETERS__VARIABLES = 0;

  /**
   * The number of structural features of the '<em>Function Call Parameters</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_PARAMETERS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.VariableCallImpl <em>Variable Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.VariableCallImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getVariableCall()
   * @generated
   */
  int VARIABLE_CALL = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_CALL__NAME = 0;

  /**
   * The number of structural features of the '<em>Variable Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_CALL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.VariableImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = ASSERTABLE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = ASSERTABLE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.StringParameterImpl <em>String Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.StringParameterImpl
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getStringParameter()
   * @generated
   */
  int STRING_PARAMETER = 21;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_PARAMETER__NAME = ASSERTABLE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_PARAMETER__VALUE = ASSERTABLE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>String Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_PARAMETER_FEATURE_COUNT = ASSERTABLE_ELEMENT_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Program#getFunctions <em>Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Functions</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Program#getFunctions()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Functions();

  /**
   * Returns the meta object for the containment reference '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Program#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Statements</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Program#getStatements()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Statements();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Functions <em>Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Functions</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Functions
   * @generated
   */
  EClass getFunctions();

  /**
   * Returns the meta object for the containment reference list '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Functions#getFunctions <em>Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Functions</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Functions#getFunctions()
   * @see #getFunctions()
   * @generated
   */
  EReference getFunctions_Functions();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Statements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statements</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Statements
   * @generated
   */
  EClass getStatements();

  /**
   * Returns the meta object for the containment reference list '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Statements#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Statements#getStatements()
   * @see #getStatements()
   * @generated
   */
  EReference getStatements_Statements();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the containment reference '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Name();

  /**
   * Returns the meta object for the containment reference '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Function#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Params</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Function#getParams()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Params();

  /**
   * Returns the meta object for the containment reference list '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Function#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Function#getStatements()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Statements();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionName <em>Function Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Name</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionName
   * @generated
   */
  EClass getFunctionName();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionName#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionName#getName()
   * @see #getFunctionName()
   * @generated
   */
  EAttribute getFunctionName_Name();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionCall <em>Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Call</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionCall
   * @generated
   */
  EClass getFunctionCall();

  /**
   * Returns the meta object for the reference '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionCall#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionCall#getRef()
   * @see #getFunctionCall()
   * @generated
   */
  EReference getFunctionCall_Ref();

  /**
   * Returns the meta object for the containment reference '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionCall#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Params</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionCall#getParams()
   * @see #getFunctionCall()
   * @generated
   */
  EReference getFunctionCall_Params();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Projection <em>Projection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Projection</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Projection
   * @generated
   */
  EClass getProjection();

  /**
   * Returns the meta object for the containment reference '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Projection#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Projection#getSelector()
   * @see #getProjection()
   * @generated
   */
  EReference getProjection_Selector();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Projection#getProjectionAction <em>Projection Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Projection Action</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Projection#getProjectionAction()
   * @see #getProjection()
   * @generated
   */
  EAttribute getProjection_ProjectionAction();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.AssertEquals <em>Assert Equals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assert Equals</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.AssertEquals
   * @generated
   */
  EClass getAssertEquals();

  /**
   * Returns the meta object for the containment reference list '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.AssertEquals#getAssertableElement <em>Assertable Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Assertable Element</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.AssertEquals#getAssertableElement()
   * @see #getAssertEquals()
   * @generated
   */
  EReference getAssertEquals_AssertableElement();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.AssertContains <em>Assert Contains</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assert Contains</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.AssertContains
   * @generated
   */
  EClass getAssertContains();

  /**
   * Returns the meta object for the containment reference '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.AssertContains#getContainer <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Container</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.AssertContains#getContainer()
   * @see #getAssertContains()
   * @generated
   */
  EReference getAssertContains_Container();

  /**
   * Returns the meta object for the containment reference '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.AssertContains#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Element</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.AssertContains#getElement()
   * @see #getAssertContains()
   * @generated
   */
  EReference getAssertContains_Element();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.AssertableElement <em>Assertable Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assertable Element</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.AssertableElement
   * @generated
   */
  EClass getAssertableElement();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.NavigationAction <em>Navigation Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Navigation Action</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.NavigationAction
   * @generated
   */
  EClass getNavigationAction();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.NavigationAction#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.NavigationAction#getAction()
   * @see #getNavigationAction()
   * @generated
   */
  EAttribute getNavigationAction_Action();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.NavigationAction#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Param</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.NavigationAction#getParam()
   * @see #getNavigationAction()
   * @generated
   */
  EAttribute getNavigationAction_Param();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.OneParameterAction <em>One Parameter Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>One Parameter Action</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.OneParameterAction
   * @generated
   */
  EClass getOneParameterAction();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.OneParameterAction#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.OneParameterAction#getAction()
   * @see #getOneParameterAction()
   * @generated
   */
  EAttribute getOneParameterAction_Action();

  /**
   * Returns the meta object for the containment reference '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.OneParameterAction#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.OneParameterAction#getSelector()
   * @see #getOneParameterAction()
   * @generated
   */
  EReference getOneParameterAction_Selector();

  /**
   * Returns the meta object for the containment reference '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.OneParameterAction#getSelectorParameter <em>Selector Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector Parameter</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.OneParameterAction#getSelectorParameter()
   * @see #getOneParameterAction()
   * @generated
   */
  EReference getOneParameterAction_SelectorParameter();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.OneParameterAction#getStringParameter <em>String Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String Parameter</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.OneParameterAction#getStringParameter()
   * @see #getOneParameterAction()
   * @generated
   */
  EAttribute getOneParameterAction_StringParameter();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.TwoParametersAction <em>Two Parameters Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Two Parameters Action</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.TwoParametersAction
   * @generated
   */
  EClass getTwoParametersAction();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.TwoParametersAction#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.TwoParametersAction#getAction()
   * @see #getTwoParametersAction()
   * @generated
   */
  EAttribute getTwoParametersAction_Action();

  /**
   * Returns the meta object for the containment reference '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.TwoParametersAction#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.TwoParametersAction#getSelector()
   * @see #getTwoParametersAction()
   * @generated
   */
  EReference getTwoParametersAction_Selector();

  /**
   * Returns the meta object for the containment reference '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.TwoParametersAction#getParameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameter</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.TwoParametersAction#getParameter()
   * @see #getTwoParametersAction()
   * @generated
   */
  EReference getTwoParametersAction_Parameter();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Selector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selector</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Selector
   * @generated
   */
  EClass getSelector();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Selector#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Element</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Selector#getElement()
   * @see #getSelector()
   * @generated
   */
  EAttribute getSelector_Element();

  /**
   * Returns the meta object for the containment reference '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Selector#getAttrs <em>Attrs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attrs</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Selector#getAttrs()
   * @see #getSelector()
   * @generated
   */
  EReference getSelector_Attrs();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Selector#isAll <em>All</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>All</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Selector#isAll()
   * @see #getSelector()
   * @generated
   */
  EAttribute getSelector_All();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Attributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attributes</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Attributes
   * @generated
   */
  EClass getAttributes();

  /**
   * Returns the meta object for the containment reference list '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Attributes#getAttrs <em>Attrs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attrs</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Attributes#getAttrs()
   * @see #getAttributes()
   * @generated
   */
  EReference getAttributes_Attrs();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Attribute#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Attribute#getValue()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Value();

  /**
   * Returns the meta object for the reference '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Attribute#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Val</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Attribute#getVal()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Val();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionParameters <em>Function Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Parameters</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionParameters
   * @generated
   */
  EClass getFunctionParameters();

  /**
   * Returns the meta object for the containment reference list '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionParameters#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionParameters#getVariables()
   * @see #getFunctionParameters()
   * @generated
   */
  EReference getFunctionParameters_Variables();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionCallParameters <em>Function Call Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Call Parameters</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionCallParameters
   * @generated
   */
  EClass getFunctionCallParameters();

  /**
   * Returns the meta object for the containment reference list '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionCallParameters#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.FunctionCallParameters#getVariables()
   * @see #getFunctionCallParameters()
   * @generated
   */
  EReference getFunctionCallParameters_Variables();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.VariableCall <em>Variable Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Call</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.VariableCall
   * @generated
   */
  EClass getVariableCall();

  /**
   * Returns the meta object for the reference '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.VariableCall#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.VariableCall#getName()
   * @see #getVariableCall()
   * @generated
   */
  EReference getVariableCall_Name();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for class '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.StringParameter <em>String Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Parameter</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.StringParameter
   * @generated
   */
  EClass getStringParameter();

  /**
   * Returns the meta object for the attribute '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.StringParameter#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.imta.clementdamien.dsl.selenium.mySelenium.StringParameter#getValue()
   * @see #getStringParameter()
   * @generated
   */
  EAttribute getStringParameter_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MySeleniumFactory getMySeleniumFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.ProgramImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Functions</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__FUNCTIONS = eINSTANCE.getProgram_Functions();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__STATEMENTS = eINSTANCE.getProgram_Statements();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionsImpl <em>Functions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionsImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getFunctions()
     * @generated
     */
    EClass FUNCTIONS = eINSTANCE.getFunctions();

    /**
     * The meta object literal for the '<em><b>Functions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTIONS__FUNCTIONS = eINSTANCE.getFunctions_Functions();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.StatementsImpl <em>Statements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.StatementsImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getStatements()
     * @generated
     */
    EClass STATEMENTS = eINSTANCE.getStatements();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENTS__STATEMENTS = eINSTANCE.getStatements_Statements();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__PARAMS = eINSTANCE.getFunction_Params();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__STATEMENTS = eINSTANCE.getFunction_Statements();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionNameImpl <em>Function Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionNameImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getFunctionName()
     * @generated
     */
    EClass FUNCTION_NAME = eINSTANCE.getFunctionName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION_NAME__NAME = eINSTANCE.getFunctionName_Name();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionCallImpl <em>Function Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionCallImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getFunctionCall()
     * @generated
     */
    EClass FUNCTION_CALL = eINSTANCE.getFunctionCall();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL__REF = eINSTANCE.getFunctionCall_Ref();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL__PARAMS = eINSTANCE.getFunctionCall_Params();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.ProjectionImpl <em>Projection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.ProjectionImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getProjection()
     * @generated
     */
    EClass PROJECTION = eINSTANCE.getProjection();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECTION__SELECTOR = eINSTANCE.getProjection_Selector();

    /**
     * The meta object literal for the '<em><b>Projection Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECTION__PROJECTION_ACTION = eINSTANCE.getProjection_ProjectionAction();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.StatementImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AssertEqualsImpl <em>Assert Equals</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AssertEqualsImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getAssertEquals()
     * @generated
     */
    EClass ASSERT_EQUALS = eINSTANCE.getAssertEquals();

    /**
     * The meta object literal for the '<em><b>Assertable Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSERT_EQUALS__ASSERTABLE_ELEMENT = eINSTANCE.getAssertEquals_AssertableElement();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AssertContainsImpl <em>Assert Contains</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AssertContainsImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getAssertContains()
     * @generated
     */
    EClass ASSERT_CONTAINS = eINSTANCE.getAssertContains();

    /**
     * The meta object literal for the '<em><b>Container</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSERT_CONTAINS__CONTAINER = eINSTANCE.getAssertContains_Container();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSERT_CONTAINS__ELEMENT = eINSTANCE.getAssertContains_Element();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AssertableElementImpl <em>Assertable Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AssertableElementImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getAssertableElement()
     * @generated
     */
    EClass ASSERTABLE_ELEMENT = eINSTANCE.getAssertableElement();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.NavigationActionImpl <em>Navigation Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.NavigationActionImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getNavigationAction()
     * @generated
     */
    EClass NAVIGATION_ACTION = eINSTANCE.getNavigationAction();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAVIGATION_ACTION__ACTION = eINSTANCE.getNavigationAction_Action();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAVIGATION_ACTION__PARAM = eINSTANCE.getNavigationAction_Param();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.OneParameterActionImpl <em>One Parameter Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.OneParameterActionImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getOneParameterAction()
     * @generated
     */
    EClass ONE_PARAMETER_ACTION = eINSTANCE.getOneParameterAction();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ONE_PARAMETER_ACTION__ACTION = eINSTANCE.getOneParameterAction_Action();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ONE_PARAMETER_ACTION__SELECTOR = eINSTANCE.getOneParameterAction_Selector();

    /**
     * The meta object literal for the '<em><b>Selector Parameter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ONE_PARAMETER_ACTION__SELECTOR_PARAMETER = eINSTANCE.getOneParameterAction_SelectorParameter();

    /**
     * The meta object literal for the '<em><b>String Parameter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ONE_PARAMETER_ACTION__STRING_PARAMETER = eINSTANCE.getOneParameterAction_StringParameter();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.TwoParametersActionImpl <em>Two Parameters Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.TwoParametersActionImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getTwoParametersAction()
     * @generated
     */
    EClass TWO_PARAMETERS_ACTION = eINSTANCE.getTwoParametersAction();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TWO_PARAMETERS_ACTION__ACTION = eINSTANCE.getTwoParametersAction_Action();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TWO_PARAMETERS_ACTION__SELECTOR = eINSTANCE.getTwoParametersAction_Selector();

    /**
     * The meta object literal for the '<em><b>Parameter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TWO_PARAMETERS_ACTION__PARAMETER = eINSTANCE.getTwoParametersAction_Parameter();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.SelectorImpl <em>Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.SelectorImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getSelector()
     * @generated
     */
    EClass SELECTOR = eINSTANCE.getSelector();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR__ELEMENT = eINSTANCE.getSelector_Element();

    /**
     * The meta object literal for the '<em><b>Attrs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTOR__ATTRS = eINSTANCE.getSelector_Attrs();

    /**
     * The meta object literal for the '<em><b>All</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR__ALL = eINSTANCE.getSelector_All();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AttributesImpl <em>Attributes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AttributesImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getAttributes()
     * @generated
     */
    EClass ATTRIBUTES = eINSTANCE.getAttributes();

    /**
     * The meta object literal for the '<em><b>Attrs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTES__ATTRS = eINSTANCE.getAttributes_Attrs();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.AttributeImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__VALUE = eINSTANCE.getAttribute_Value();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__VAL = eINSTANCE.getAttribute_Val();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionParametersImpl <em>Function Parameters</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionParametersImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getFunctionParameters()
     * @generated
     */
    EClass FUNCTION_PARAMETERS = eINSTANCE.getFunctionParameters();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_PARAMETERS__VARIABLES = eINSTANCE.getFunctionParameters_Variables();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionCallParametersImpl <em>Function Call Parameters</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.FunctionCallParametersImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getFunctionCallParameters()
     * @generated
     */
    EClass FUNCTION_CALL_PARAMETERS = eINSTANCE.getFunctionCallParameters();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL_PARAMETERS__VARIABLES = eINSTANCE.getFunctionCallParameters_Variables();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.VariableCallImpl <em>Variable Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.VariableCallImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getVariableCall()
     * @generated
     */
    EClass VARIABLE_CALL = eINSTANCE.getVariableCall();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_CALL__NAME = eINSTANCE.getVariableCall_Name();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.VariableImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link fr.imta.clementdamien.dsl.selenium.mySelenium.impl.StringParameterImpl <em>String Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.StringParameterImpl
     * @see fr.imta.clementdamien.dsl.selenium.mySelenium.impl.MySeleniumPackageImpl#getStringParameter()
     * @generated
     */
    EClass STRING_PARAMETER = eINSTANCE.getStringParameter();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_PARAMETER__VALUE = eINSTANCE.getStringParameter_Value();

  }

} //MySeleniumPackage
