/**
 * generated by Xtext 2.12.0
 */
package fr.imta.clementdamien.dsl.selenium.mySelenium;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.imta.clementdamien.dsl.selenium.mySelenium.MySeleniumPackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
} // Program
