/*
 * generated by Xtext 2.12.0
 */
package fr.imta.clementdamien.dsl.selenium.serializer;

import com.google.inject.Inject;
import fr.imta.clementdamien.dsl.selenium.services.MySeleniumGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class MySeleniumSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MySeleniumGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Program_CommentParserRuleCall_0_a;
	protected AbstractElementAlias match_Program_CommentParserRuleCall_2_a;
	protected AbstractElementAlias match_Selector_AllKeyword_4_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MySeleniumGrammarAccess) access;
		match_Program_CommentParserRuleCall_0_a = new TokenAlias(true, true, grammarAccess.getProgramAccess().getCommentParserRuleCall_0());
		match_Program_CommentParserRuleCall_2_a = new TokenAlias(true, true, grammarAccess.getProgramAccess().getCommentParserRuleCall_2());
		match_Selector_AllKeyword_4_q = new TokenAlias(false, true, grammarAccess.getSelectorAccess().getAllKeyword_4());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getCommentRule())
			return getCommentToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getSTRINGRule())
			return getSTRINGToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * Comment:
	 * 	"#" + STRING 
	 * ;
	 */
	protected String getCommentToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "#\"\"";
	}
	
	/**
	 * terminal STRING	: 
	 * 			'"' ( '\\' .  | !('\\'|'"') )* '"' |
	 * 			"'" ( '\\' .  | !('\\'|"'") )* "'"
	 * 		;
	 */
	protected String getSTRINGToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "\"\"";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Program_CommentParserRuleCall_0_a.equals(syntax))
				emit_Program_CommentParserRuleCall_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Program_CommentParserRuleCall_2_a.equals(syntax))
				emit_Program_CommentParserRuleCall_2_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Selector_AllKeyword_4_q.equals(syntax))
				emit_Selector_AllKeyword_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     Comment*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) functions+=Function
	 */
	protected void emit_Program_CommentParserRuleCall_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     Comment*
	 *
	 * This ambiguous syntax occurs at:
	 *     functions+=Function (ambiguity) (rule end)
	 */
	protected void emit_Program_CommentParserRuleCall_2_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '.all'?
	 *
	 * This ambiguous syntax occurs at:
	 *     attrs=Attributes ']' (ambiguity) (rule end)
	 *     element=DOMElement '[' ']' (ambiguity) (rule end)
	 */
	protected void emit_Selector_AllKeyword_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
