/*
 * generated by Xtext 2.12.0
 */
package fr.imta.clementdamien.dsl.selenium


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MySeleniumRuntimeModule extends AbstractMySeleniumRuntimeModule {
}
