/*
 * generated by Xtext 2.12.0
 */
package fr.imta.clementdamien.dsl.selenium.ide.contentassist.antlr;

import com.google.inject.Inject;
import fr.imta.clementdamien.dsl.selenium.ide.contentassist.antlr.internal.InternalMySeleniumParser;
import fr.imta.clementdamien.dsl.selenium.services.MySeleniumGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MySeleniumParser extends AbstractContentAssistParser {

	@Inject
	private MySeleniumGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalMySeleniumParser createParser() {
		InternalMySeleniumParser result = new InternalMySeleniumParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getProgramAccess().getAlternatives(), "rule__Program__Alternatives");
					put(grammarAccess.getProjectionActionAccess().getAlternatives(), "rule__ProjectionAction__Alternatives");
					put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
					put(grammarAccess.getAssertableElementAccess().getAlternatives(), "rule__AssertableElement__Alternatives");
					put(grammarAccess.getNavigationActionTypeAccess().getAlternatives(), "rule__NavigationActionType__Alternatives");
					put(grammarAccess.getActionTargetAccess().getAlternatives(), "rule__ActionTarget__Alternatives");
					put(grammarAccess.getActionParameterAccess().getAlternatives(), "rule__ActionParameter__Alternatives");
					put(grammarAccess.getAttributeAccess().getAlternatives_2(), "rule__Attribute__Alternatives_2");
					put(grammarAccess.getDOMAttributeAccess().getAlternatives(), "rule__DOMAttribute__Alternatives");
					put(grammarAccess.getDOMElementAccess().getAlternatives(), "rule__DOMElement__Alternatives");
					put(grammarAccess.getActionTypeAccess().getAlternatives(), "rule__ActionType__Alternatives");
					put(grammarAccess.getVariableCallAccess().getAlternatives(), "rule__VariableCall__Alternatives");
					put(grammarAccess.getFunctionsAccess().getGroup(), "rule__Functions__Group__0");
					put(grammarAccess.getMainFunctionAccess().getGroup(), "rule__MainFunction__Group__0");
					put(grammarAccess.getFunctionAccess().getGroup(), "rule__Function__Group__0");
					put(grammarAccess.getFunctionCallAccess().getGroup(), "rule__FunctionCall__Group__0");
					put(grammarAccess.getProjectionAccess().getGroup(), "rule__Projection__Group__0");
					put(grammarAccess.getAssertEqualsAccess().getGroup(), "rule__AssertEquals__Group__0");
					put(grammarAccess.getAssertContainsAccess().getGroup(), "rule__AssertContains__Group__0");
					put(grammarAccess.getNavigationActionAccess().getGroup(), "rule__NavigationAction__Group__0");
					put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
					put(grammarAccess.getAssignActionAccess().getGroup(), "rule__AssignAction__Group__0");
					put(grammarAccess.getSelectorAccess().getGroup(), "rule__Selector__Group__0");
					put(grammarAccess.getSelectorAccess().getGroup_4(), "rule__Selector__Group_4__0");
					put(grammarAccess.getParentAccess().getGroup(), "rule__Parent__Group__0");
					put(grammarAccess.getAttributesAccess().getGroup(), "rule__Attributes__Group__0");
					put(grammarAccess.getAttributesAccess().getGroup_1(), "rule__Attributes__Group_1__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getFunctionParametersAccess().getGroup(), "rule__FunctionParameters__Group__0");
					put(grammarAccess.getFunctionParametersAccess().getGroup_2(), "rule__FunctionParameters__Group_2__0");
					put(grammarAccess.getFunctionCallParametersAccess().getGroup(), "rule__FunctionCallParameters__Group__0");
					put(grammarAccess.getFunctionCallParametersAccess().getGroup_1(), "rule__FunctionCallParameters__Group_1__0");
					put(grammarAccess.getFunctionCallParametersAccess().getGroup_1_1(), "rule__FunctionCallParameters__Group_1_1__0");
					put(grammarAccess.getFunctionsAccess().getFunctionsAssignment_0(), "rule__Functions__FunctionsAssignment_0");
					put(grammarAccess.getFunctionsAccess().getMainFunctionAssignment_1(), "rule__Functions__MainFunctionAssignment_1");
					put(grammarAccess.getStatementsAccess().getStatementsAssignment(), "rule__Statements__StatementsAssignment");
					put(grammarAccess.getMainFunctionAccess().getStatementsAssignment_3(), "rule__MainFunction__StatementsAssignment_3");
					put(grammarAccess.getFunctionAccess().getNameAssignment_1(), "rule__Function__NameAssignment_1");
					put(grammarAccess.getFunctionAccess().getParamsAssignment_2(), "rule__Function__ParamsAssignment_2");
					put(grammarAccess.getFunctionAccess().getStatementsAssignment_4(), "rule__Function__StatementsAssignment_4");
					put(grammarAccess.getFunctionNameAccess().getNameAssignment(), "rule__FunctionName__NameAssignment");
					put(grammarAccess.getFunctionCallAccess().getRefAssignment_0(), "rule__FunctionCall__RefAssignment_0");
					put(grammarAccess.getFunctionCallAccess().getParamsAssignment_1(), "rule__FunctionCall__ParamsAssignment_1");
					put(grammarAccess.getProjectionAccess().getSelectorAssignment_0(), "rule__Projection__SelectorAssignment_0");
					put(grammarAccess.getProjectionAccess().getProjectionActionAssignment_2(), "rule__Projection__ProjectionActionAssignment_2");
					put(grammarAccess.getAssertEqualsAccess().getAssertableElementAssignment_1(), "rule__AssertEquals__AssertableElementAssignment_1");
					put(grammarAccess.getAssertEqualsAccess().getAssertableElementAssignment_3(), "rule__AssertEquals__AssertableElementAssignment_3");
					put(grammarAccess.getAssertContainsAccess().getContainerAssignment_1(), "rule__AssertContains__ContainerAssignment_1");
					put(grammarAccess.getAssertContainsAccess().getElementAssignment_3(), "rule__AssertContains__ElementAssignment_3");
					put(grammarAccess.getNavigationActionAccess().getActionAssignment_0(), "rule__NavigationAction__ActionAssignment_0");
					put(grammarAccess.getNavigationActionAccess().getParamAssignment_1(), "rule__NavigationAction__ParamAssignment_1");
					put(grammarAccess.getActionAccess().getActionAssignment_0(), "rule__Action__ActionAssignment_0");
					put(grammarAccess.getActionAccess().getTargetAssignment_1(), "rule__Action__TargetAssignment_1");
					put(grammarAccess.getActionAccess().getParamAssignment_2(), "rule__Action__ParamAssignment_2");
					put(grammarAccess.getAssignActionAccess().getTargetAssignment_1(), "rule__AssignAction__TargetAssignment_1");
					put(grammarAccess.getAssignActionAccess().getVariableAssignment_2(), "rule__AssignAction__VariableAssignment_2");
					put(grammarAccess.getActionParameterStringAccess().getValueAssignment(), "rule__ActionParameterString__ValueAssignment");
					put(grammarAccess.getSelectorAccess().getElementAssignment_0(), "rule__Selector__ElementAssignment_0");
					put(grammarAccess.getSelectorAccess().getAttrsAssignment_2(), "rule__Selector__AttrsAssignment_2");
					put(grammarAccess.getSelectorAccess().getParentAssignment_4_2(), "rule__Selector__ParentAssignment_4_2");
					put(grammarAccess.getSelectorAccess().getAllAssignment_5(), "rule__Selector__AllAssignment_5");
					put(grammarAccess.getParentAccess().getElementAssignment_0(), "rule__Parent__ElementAssignment_0");
					put(grammarAccess.getParentAccess().getAttrsAssignment_2(), "rule__Parent__AttrsAssignment_2");
					put(grammarAccess.getAttributesAccess().getAttrsAssignment_0(), "rule__Attributes__AttrsAssignment_0");
					put(grammarAccess.getAttributesAccess().getAttrsAssignment_1_1(), "rule__Attributes__AttrsAssignment_1_1");
					put(grammarAccess.getAttributeAccess().getNameAssignment_0(), "rule__Attribute__NameAssignment_0");
					put(grammarAccess.getAttributeAccess().getValueAssignment_2_0(), "rule__Attribute__ValueAssignment_2_0");
					put(grammarAccess.getAttributeAccess().getVariableAssignment_2_1(), "rule__Attribute__VariableAssignment_2_1");
					put(grammarAccess.getFunctionParametersAccess().getVariablesAssignment_1(), "rule__FunctionParameters__VariablesAssignment_1");
					put(grammarAccess.getFunctionParametersAccess().getVariablesAssignment_2_1(), "rule__FunctionParameters__VariablesAssignment_2_1");
					put(grammarAccess.getFunctionCallParametersAccess().getVariablesAssignment_1_0(), "rule__FunctionCallParameters__VariablesAssignment_1_0");
					put(grammarAccess.getFunctionCallParametersAccess().getVariablesAssignment_1_1_1(), "rule__FunctionCallParameters__VariablesAssignment_1_1_1");
					put(grammarAccess.getVariableRefAccess().getRefAssignment(), "rule__VariableRef__RefAssignment");
					put(grammarAccess.getVariableAccess().getNameAssignment(), "rule__Variable__NameAssignment");
					put(grammarAccess.getStringParameterAccess().getValueAssignment(), "rule__StringParameter__ValueAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MySeleniumGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MySeleniumGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
