/*
 * generated by Xtext 2.12.0
 */
package fr.imta.clementdamien.dsl.selenium.ui;

import com.google.inject.Injector;
import fr.imta.clementdamien.dsl.selenium.ui.internal.SeleniumActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MySeleniumExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SeleniumActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SeleniumActivator.getInstance().getInjector(SeleniumActivator.FR_IMTA_CLEMENTDAMIEN_DSL_SELENIUM_MYSELENIUM);
	}
	
}
